title: Ariel's Playground
description: Experiments and small projects
permalink: /:slugified_categories/:title/

date_format: "%b %-d, %Y"

jekyll_compose:
  auto_open: true

exclude:
  - "package*.json"
  - "*.config.js"
  - netlify.toml
  - README.md
  - LICENSE
  - Makefile
